### ISSUE TITLE
Managing browser updates

### ISSUE THREAD

**Issue by Skahrz** [Valve/fingerprintjs2#97] opened 2015-12-10 10:35 UTC
Is there any way to use this library with taking care of browser version ?

I mean browser v1 print is deep equal to browser v2 print ?

**Comment by Valve** [comment] 2015-12-10 12:40
Yes, I need to implement use agent parser to take the UserAgent minus version. This is the next thing on my todo list. Any help is apprerciated.

**Comment by Valve** [comment] 2015-12-18 08:49
Duplicate of #5

**Closed by Valve** 2015-12-18 08:49 UTC
