### ISSUE TITLE
Example using ES6/React?

### ISSUE THREAD

**Issue by Orbyt** [Valve/fingerprintjs2#216] opened 2016-12-16 21:19 UTC
Is there an example of using this with ES6? I've tried importing it into my React component a few different ways:

```
import { Fingerprint2 } from 'fingerprintjs2'

export default class Component extends React.Component {

	constructor(props) {
		super(props);
		  Fingerprint2().get(function(result, components) { //Error
		  console.log(result); 
		  console.log(components);
		});
```

But keep getting `fingerprintjs.Fingerprint2 is not a function` in the console.

**Comment by Valve** [comment] 2016-12-16 21:20
No, no example, I'm not using React, sorry

**Comment by Orbyt** [comment] 2016-12-16 21:22
Any thoughts on why the error might be thrown? Using it as a constructor is also invalid `_fingerprintjs.Fingerprint2 is not a constructor`

**Comment by Valve** [comment] 2016-12-16 21:23
Probably a module export issue

**Comment by binarytracer** [comment] 2017-01-11 06:59
how about like this?

version 2, will be supporting "synchronous way".

``` js
import React from 'react';
import Fingerprint from 'fingerprintjs2';

const fpInstance = new Fingerprint();

export default
class FingerPrintComponent extends React.Component {

	constructor(){
		super();
		this.state = {result: null};
	}

	componentWillMount(){

		const stuff = this;

		fpInstance.get((result)=> {

				stuff.setState({fpsignature: result});
		});


	}

	render(){

		const {fpsignature} = this.state;

		if( ! fpsignature ) {
			return (<div> waiting ...  </div>);
		}

		return(
			<div style={{'textAlign':'center'}}>
				<br/>
				<br/>
				<span> Device FingerPrint </span>
				<hr />
				<h1> {fpsignature} </h1>
			</div>);
	}
}

```

**Comment by pschlette** [comment] 2017-01-24 20:36
@Orbyt I think you just need to change your import to `import Fingerprint2 from 'fingerprintjs2'`; that is, use the default export, not a named export. The sample usage on the README worked fine for me in a React app using ES6.

**Comment by mixcas** [comment] 2017-02-02 23:01
I'm using it with Meteor+React like this:

```
import { Meteor } from 'meteor/meteor';

import { compose } from 'react-komposer';
import Fingerprint2 from 'fingerprintjs2';

import { MainLayout } from '/imports/components/base/MainLayout.jsx';

const composer = (props, onData) => {

  new Fingerprint2().get((fingerprint) => {
    Session.set('fingerprint', fingerprint);
    onData(null, {});
  });

};

export const MainContainer = compose(composer)(MainLayout);
```

**Comment by Valve** [comment] 2017-02-08 16:01
please update wiki with this, closing, since it's not an issue/bug

**Closed by Valve** 2017-02-08 16:01 UTC

**Comment by JamesTheHacker** [comment] 2018-05-23 19:05
While this is not a bug it is an issue. It might be worth considering updating the module to make it easier to work with in ES6. I've been bashing my head with this problem for a while until I found this.

Whether you're using React or not it should still be possible to use ES6 imports. I use await/async and I needed to promisfy `get` (callback hell is so ES5 ... yuck) which is what stumped me and I'm sure there's many others wanting to do the same.

I don't mind submitting a PR and discussing this if this is something you're looking to do.

**Comment by cbougatsa** [comment] 2018-11-30 10:34
For me it worked when i called Fingerprint2().get() instead of Fingerprint2.get() as it currently is in the documentation example

```
import Fingerprint2 from "fingerprintjs2";

Fingerprint2().get((result, components) => {
      console.log(result);
});
```

**Comment by ValentinZhao** [comment] 2018-12-03 05:55
`@types/fingerprintjs2` does not work for now. The version of it is `1.5.6`.

The issue is you cannot import it through `import Fingerprint2 from 'fingerprintjs2';` because `d.type` does not have a default export. So for everyone who traces here and wishes to import this library using TypeScript trying code below:
```
const Fingerprint2 = require('fingerprintjs2');
const fp_instance = Fingerprint2();

setTimeout(function () {
    fp_instance.get(function (result:string, components:[{ key:string, value:string }]) {
        const fingerprint = fp_instance.x64hash128(components.map(function (pair:any) { return pair.value; }).join(), 31);
        res(fingerprint);
    });
}, 500);
```
We just import the code directly from `dist/fingerprintjs2.min.js`.

**Comment by gfiury** [comment] 2020-01-09 14:48
The instance of Fingerprint2 is deprecated, looking at the README shows the new way

Fingerprint2.get(options, function (components) {
    var values = components.map(function (component) { return component.value })
    var murmur = Fingerprint2.x64hash128(values.join(''), 31)
})
