### ISSUE TITLE
I fresh index.html on IE11 ,then I get a different key.

### ISSUE THREAD

**Issue by misslv** [Valve/fingerprintjs2#171] opened 2016-07-27 01:32 UTC

**Comment by misslv** [comment] 2016-07-27 01:35
It works well on Chrome,but it has a problem on ie11.I fresh the page and I get a new key.

**Comment by Valve** [comment] 2016-07-28 09:18
I cannot reproduce it. I'm using browserstack.com to test it, but the FP remains consistent for me when I refresh/open new tabs + refresh etc.
I'm closing this issue now, feel free to reopen with a specific fingerprinting component that is changing for you in IE11 from tab to tab.

**Closed by Valve** 2016-07-28 09:18 UTC
