### ISSUE TITLE
Use BatteryManager API

### ISSUE THREAD

**Issue by cjbrowne** [Valve/fingerprintjs2#203] opened 2016-11-01 13:23 UTC
The BatteryManager API can be used to intuit the capacity of a user's battery.  This information can be used to further distinguish between users, as battery capacities change over time.

**Comment by Valve** [comment] 2016-11-01 14:25
Thanks for submitting this idea.
Unfortunately, this ticket is a duplicate of https://github.com/Valve/fingerprintjs2/issues/55

**Closed by Valve** 2016-11-01 14:25 UTC
