### ISSUE TITLE
Safari 3 fingerprints

### ISSUE THREAD

**Issue by webhat** [Valve/fingerprintjs2#63] opened 2015-08-01 17:38 UTC
I'm running Safari (Version 8.0.7 (10600.7.12)) without Flash it seems to alternate between 3 different fingerprints for the same browser in the same session.

I'm using the example code from the `README.md`:

```javascript
(function () {
  new Fingerprint2().get(function(result){
      console.log(result);
  });
})();
```

**Comment by Valve** [comment] 2015-08-02 05:15
Duplicate of #62

**Closed by Valve** 2015-08-02 05:15 UTC
