### ISSUE TITLE
different fingerprint value in iframe and out of iframe in firefox

### ISSUE THREAD

**Issue by alirezaDavid** [Valve/fingerprintjs2#118] opened 2016-01-24 10:36 UTC
In firefox browser fingerprint in iframe and fingerprint out of iframe not the same.
Thanks

**Comment by Valve** [comment] 2016-01-25 10:14
Thanks for letting me know, I will look into it

**Comment by Valve** [comment] 2016-02-07 03:05
Just as an update, I'm currently not working on the library because I'm traveling, but I will definitely look into it

**Comment by alirezaDavid** [comment] 2016-02-07 07:29
@Valve Thanks buddy

**Comment by alirezaDavid** [comment] 2016-03-01 05:51
**UPDATE**
I found this issue also in android browser and firefox mobile.

**Comment by Valve** [comment] 2016-03-12 14:44
@alirezaDavid hi, thanks for waiting :) Could you please send a link to jsbin or similar to reproduce?

**Comment by Valve** [comment] 2016-08-08 07:11
closing due to inability to reproduce and lack of JavaScript example on JSbin or similar.

**Closed by Valve** 2016-08-08 07:11 UTC
