### ISSUE TITLE
the fingerprint alway the same in all iphoneX device with same os version (11.4)

### ISSUE THREAD

**Issue by NeOEBoy** [Valve/fingerprintjs2#340] opened 2018-07-13 01:22 UTC
Before submitting an issue:

- Read this: https://github.com/Valve/fingerprintjs2/blob/master/FAQ.md
- Follow these instructions: https://github.com/Valve/fingerprintjs2/blob/master/CONTRIBUTING.md

1) I checked that my issue is not already fixed in GitHub master:
No
2) My fingerprint retrieved with [this jsfiddle](https://jsfiddle.net/L2gLq4rg/) is:
   ```
   ...
   ```
sorry for can't open https://jsfiddle.net/L2gLq4rg/ website

3) My device is:
iPhoneX

**Comment by jonashaag** [comment] 2018-07-13 05:11
Duplicate of #125, #122, #209

**Closed by jonashaag** 2018-07-13 05:11 UTC
