### ISSUE TITLE
repeat rate 80%?

### ISSUE THREAD

**Issue by weijl6819** [Valve/fingerprintjs2#513] opened 2020-01-17 10:30 UTC
I have test in 1200 people via canvas and webGL, only 200different fingerprints?

**Comment by jonashaag** [comment] 2020-01-17 10:46
Interesting. Do you have user agent/device model statistics?

**Comment by Valve** [comment] 2020-01-17 15:13
@weijl6819 how many unique browsers did you have out of those 1200?
If you had only 200 unique browsers, you will have 200 different fingerprints.

iPhone browsers are very unique in this regard, if you go to an Apple Store and try Fingerprint.js on all latest iPhone 11, you will have identical fingerprints. 

For truly unique identification, I recommend using our PRO service: https://fingerprintjs.com.
The free version is a browser hash and nothing more, it does not deduplicate between identical devices.

**Comment by Valve** [comment] 2020-01-17 15:14
Closing now as not a bug, please feel free to re-open with more details @weijl6819

**Closed by Valve** 2020-01-17 15:14 UTC
