### ISSUE TITLE
Same hash and different IP address

### ISSUE THREAD

**Issue by chiborg** [Valve/fingerprintjs2#297] opened 2018-01-19 18:48 UTC
I'm trying the code on a website to identify browsers and I see the result: the generated hash code is same but the IP address is different.
The options was:

options = {
	excludeAdBlock: true,
	excludeWebGL: true,
	excludeDoNotTrack: true
}

Now I deleted these options, but what options will not cause this result?

**Comment by jonashaag** [comment] 2018-01-22 11:33
I don't think IP address is even part of the fingerprint? Why would that even make sense because the whole point of this library is to be able to identify devices even if their IP address has changed.

**Comment by chiborg** [comment] 2018-01-22 13:21
I know, the IP address is not part of the fingerprint. I know, why. But when I used the fingerprintjs2 on my site, I see a weird result: 20 users have same fingerprint. They are same country another city and the logins was in same hour.
I just want tips for better result, or somebody say: this things maybe happens. Their operation system and browser maybe same, and they are using same options.
I'm only want to filter that users, who have more profile to using for cheat in a vote game, and I think, the fingerprintjs2 is a good stuff for filter. But I see, it's not.

**Comment by jonashaag** [comment] 2018-01-22 13:37
OK, closing this then as it's not a bug. Feel free to use this issue a discussion forum if you want.

Maybe the 20 users are the same person (= same browser)? Or they're using a very common device (iPhone 6 or whatever) that all have the same fingerprint.

**Closed by jonashaag** 2018-01-22 13:37 UTC
